### ISSUE TITLE
Add a Readme file to the repository

### ISSUE THREAD

**Issue by sunjunkie** [anitab-org/mentorship-ios#1]
## Description
As a Developer,
I need to understand what this project is about,
so that I can contribute to the development of this project.

### Update [Required]
- [ ] Add new Readme file

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

**Comment by yugantarjain** [comment]
I've made a pull request, it's not final yet. However, I have left some blank fields and links (marked bold) and have a few doubts regarding them.
1. For "Setting up of project" links; should they redirect to a wiki page (like in android), or to a markdown file part of the repo itself?
2. Should I copy the "Contributing guidelines" and "Commit message style guide" from the android repo, or will they be different? Also, should they be files in the repo or part of the wiki?
3. I also have a doubt regarding the workflow. Should I fork the repo and make PRs from my copy, or should I directly create new branches here itself?

**Comment by sunjunkie** [comment]
1. There has not been a consistent standard so far. I've asked May if the new open source team has established a standard. For now, let's use the wiki.
2. Let's copy from Android for now.
3. Our workflow has been to fork the repo and submit PRs from there. Normally, we would create a new branch titled "gsoc20" and merge to that. Then merge that branch after gsoc. But this is a new repo so I think we will probably just use "develop".
