### ISSUE TITLE
Create UI tests for user registration screens

### ISSUE THREAD

**Issue by vatsalkul** [anitab-org/mentorship-ios#10]
## Description
As a developer, I need to ensure the quality of app, so that It will not have any UI bugs.

### Update [Required]
- [ ] Create UI tests for user registration screens (Login/SignUp)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by yugantarjain** [comment]
UI tests discarded due to SwiftUI bugs. Disucssion on PR #99
