### ISSUE TITLE
test: Add tests for report violation

### ISSUE THREAD

**Issue by vatsalkul** [anitab-org/mentorship-ios#110]
## Description
As a developer,
I need create tests for the report violation feature,
so that I can be confident the code is working properly.

### Update [Required]
- [ ] unit tests are available for this feature.
 - [ ] UI tests are available for this feature.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
4 hours

**Comment by yugantarjain** [comment]
Done in PR #111
