### ISSUE TITLE
Relation successfully sent message shown in error text UI to the user

### ISSUE THREAD

**Issue by yugantarjain** [anitab-org/mentorship-ios#123]
**Describe the bug**
When a new relation request is sent successfully, the user is notified using the same text that is used to show errors.

**To Reproduce**
1. Go to members screen
2. Tap on any member
3. Send request successfully
4. See the success message in an error text UI

**Expected behavior**
Ideally, for a successful request, an alert shall be shown with an 'Okay' button. Secondly, tapping on the 'Okay' button shall dismiss the send request sheet.

**Screenshots**
<img width="498" alt="Screen Shot 2020-08-30 at 12 36 04 PM" src="https://user-images.githubusercontent.com/31164725/91653361-a8353800-eabd-11ea-973b-c1b9a6912bda.png">

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 13.6

**Additional context**
To solve the bug (improve the UX), an alert will have to be used with a `Bool: isShowing` variable in the respective ViewModel. Secondly, to check whether the request was sent successfully or not, the status code returned by the server will have to be used (in the Networking group).

**Comment by aaryankotharii** [comment]
Hey, can I work on this issue?

**Comment by yugantarjain** [comment]
> Hey, can I work on this issue?

Sure @aaryankotharii , assigned :) Thanks!
