### ISSUE TITLE
Mentorship Logo image has white background and disrupts dark mode.

### ISSUE THREAD

**Issue by yugantarjain** [anitab-org/mentorship-ios#124]
**Describe the bug**
Mentorship Logo image used in the app has white background and stays white even in dark mode disrupting the UI of Login and About screen in dark mode.

**To Reproduce**
1. Go to Login or About screen
2. Switch to Dark Mode
3. See mentorship logo with white background

**Expected behavior**
The image should have transparent background (or some other solution) and hence automatically adapt to light/dark mode.

**Screenshots**
|Light ✅|Dark ❌|
|-----|-----|
|<img width="498" alt="Screen Shot 2020-08-30 at 2 39 01 PM" src="https://user-images.githubusercontent.com/31164725/91655504-9e680080-eace-11ea-9efb-d0a847ee0dde.png">|<img width="498" alt="Screen Shot 2020-08-30 at 1 30 03 PM" src="https://user-images.githubusercontent.com/31164725/91655515-b50e5780-eace-11ea-8bba-8e711c4f46cd.png">|

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 13.6
 - Xcode 13.6

**Comment by aaryankotharii** [comment]
Hey, Can I work on this issue?

**Comment by yugantarjain** [comment]
Hi @aaryankotharii, definitely, thanks a lot for your interest in working on this issue! 
Assigned.
