### ISSUE TITLE
Username and Password on Login screen does not reset after login

### ISSUE THREAD

**Issue by yugantarjain** [anitab-org/mentorship-ios#125]
**Describe the bug**
The username and the password of the user used for login remains preserved even after a successful login. Ideally, it should be reset.

**To Reproduce**
1. Login using username/email & password
2. Logout
3. See the username and password on the login screen

**Expected behavior**
The username and password should reset on a successful login and the text fields on login screen should be empty when a user logs out.

**Screenshots**
Username and password present on login screen appears after signing out from settings.
<img width="498" alt="image" src="https://user-images.githubusercontent.com/31164725/91655624-8644b100-eacf-11ea-8af6-6e42da62c3d6.png">

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 13.6
 - Xcode 11.6

**Comment by iMostfa** [comment]
can I work on this ? I've already fixed it before asking, so I'm asking now

**Comment by sunjunkie** [comment]
@iMostfa you may work on this issue. 😊

**Comment by arkumari2000** [comment]
I want to look into this issue.

**Comment by sunjunkie** [comment]
> I want to look into this issue.

Someone is already working on this issue.
