### ISSUE TITLE
bug: 'Add Task' button in relation screen is enabled for an empty relation too

### ISSUE THREAD

**Issue by yugantarjain** [anitab-org/mentorship-ios#128]
**Describe the bug**
The 'Add Task' button in the relation screen stays enabled even when the user is not in a mentorship relation. A task can only be added when a relation exists, hence this button shall be disabled in case the relation is nil.

**To Reproduce**
1. Withdraw from accepted relation (if any) from home screen
2. Go to relation screen
3. See 'Add Task' button is enabled (it shouldn't be)

**Expected behavior**
The 'Add Task' button should be disabled when the user is not in a relation

**Screenshots**
Add Task button is enabled
<img width="498" alt="image" src="https://user-images.githubusercontent.com/31164725/92227788-6d1f7400-eec4-11ea-9628-1d4ce4fbf12e.png">

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 13.6
 - Xcode 11.6

**Comment by gsnsg** [comment]
@yugantarjain Can I work on this issue? I got a working solution already

**Comment by yugantarjain** [comment]
> @yugantarjain Can I work on this issue? I got a working solution already

Hi @gsnsg, thanks a lot for your interest in working on this issue! I've kept this as a good first time issue due to its simplicity. 

I do have another issue in mind about improving the Relation Screen UI when the user is not in a mentorship relation (like the screenshot above). As you can see, as of now the app shows default "Mentee" and "Jan 1, 1970". We can hide them, and also have a message on the screen saying something like "You're not in a mentorship relation, you can find members and send a request from members page." and have a button that redirects the user to the members tab.
Would you like to create an issue for this and work on it?

**Comment by Zoha131** [comment]
@yugantarjain  Can I work on this issue?

**Comment by yugantarjain** [comment]
> @yugantarjain Can I work on this issue?

Hi sure. Assigned!
