### ISSUE TITLE
Home view large title truncates if name is large.

### ISSUE THREAD

**Issue by aaryankotharii** [anitab-org/mentorship-ios#131]
**Describe the bug**
Home view large title truncates if full name is entered.

**To Reproduce**
1. Edit and enter full name in profile.
2. Go to Home View.  
3. See title of home view.

**Expected behavior**
The title should not truncate and entire title should be legible.

**Screenshots**
| Truncating Title ❌|
| ------------- | 
|<img src="https://user-images.githubusercontent.com/53724307/93003708-a4de8980-f55e-11ea-8aca-4a6e55f0bead.png" width="200"> |

**Smartphone (please complete the following information):**
- Simulator: iPhone 11 Pro
- OS: iOS 13.7
- Xcode 11.7

**Additional context**
One probable fix is to is to consider only first name (i.e first word of name string) for the title here.

**Comment by yugantarjain** [comment]
Hi again @aaryankotharii :) Do you want to work on this issue or do you want to keep it open to other contributors?
Also, thanks for submitting this issue.

**Comment by aaryankotharii** [comment]
@yugantarjain How about we keep it open to other contributors and if no one picks it up, I will work on this.

**Comment by rarcilla** [comment]
Hi! I'm interested on working on this issue if its still available! I'm new to OSS, but have Swift and some SwiftUI experience :)

**Comment by yugantarjain** [comment]
Hi @rarcilla, sure, assigned. Thanks a lot for your interest in contributing to the Mentorship iOS project!

**Comment by rarcilla** [comment]
I was reading the comments under other issue #139, I was also under the assumption that this issue was eligible for Hacktoberfest and I wasn't aware of the update, so I will unassign myself! Thanks for your consideration.

**Comment by R-Cole** [comment]
Hi I would like to work on this issue, what is the process to getting assigned?

**Comment by yugantarjain** [comment]
Hi @R-Cole, assigned! Thanks for your interest in working on this issue!

**Comment by R-Cole** [comment]
You bet, glad to help out if I can

**Comment by R-Cole** [comment]
Hi, just wondering if there is a test User account for logging in with? I am registering/logging in using the plain way (not Google or Apple) and It keeps saying to "Please verify your email before login." after I register and try to login...

**Comment by yugantarjain** [comment]
> Hi, just wondering if there is a test User account for logging in with? I am registering/logging in using the plain way (not Google or Apple) and It keeps saying to "Please verify your email before login." after I register and try to login...

You must have got a verification link on your email, just click on that and you'll be able to login after that...

**Comment by R-Cole** [comment]
I was thinking I would get a verification email and none has arrived. I will try some more.

**Comment by yugantarjain** [comment]
You can use the backend Swagger UI to resend yourself the verification email. 
https://mentorship-backend-temp.herokuapp.com
Also, try checking the spam folder...

**Comment by R-Cole** [comment]
Thx, it of course worked when I tried it again, maybe other times I didnt get email exactly right. Ok should be all good now.
