### ISSUE TITLE
Change Password error still visible after success.

### ISSUE THREAD

**Issue by aaryankotharii** [anitab-org/mentorship-ios#134]
**Describe the bug**
once password is changed successfully and user taps on `okay`, The red error label is briefly visible while the screen dismisses.

**To Reproduce**
1. Go to ChangePassword View.
2. Change your password.
3. Click okay.
4. See error label.

**Expected behaviour**
If change  password is successful , error label should be hidden.

**Screenshots**
<img src="https://user-images.githubusercontent.com/53724307/93313850-a2ae5080-f826-11ea-80b8-52d2ed835285.gif" width="300"/>

**Simulator:**
 - Device: iPhone 11 Pro
 - iOS: 13.7
 - Xcode: 11.7

**Comment by aaryankotharii** [comment]
Hey, can I be assigned to this issue.

**Comment by yugantarjain** [comment]
> Hey, can I be assigned to this issue.

Sure, assigned.

**Comment by aaryankotharii** [comment]
Thank you!
