### ISSUE TITLE
ChangePassword View does not reset after success.

### ISSUE THREAD

**Issue by aaryankotharii** [anitab-org/mentorship-ios#135]
**Describe the bug**
The textfields and error label in change password view do no reset after a successful password change.

**To Reproduce**
1. Go to ChangePassword View.
2. Change your password.
3. The view will dismiss once you click `okay`
4. Tap on ChangePassword again.
5. The fields will not be reset.

**Expected behavior**
All fields and labels should be empty.

**Screenshots**
<img src = "https://user-images.githubusercontent.com/53724307/93416346-42212100-f8c3-11ea-8a73-03f08b4b617c.png" width = "200" >

**Simulator (please complete the following information):**
 - iPhone : 11 pro
 - iOS : 13.7
 - Xcode : 11.7

**Additional context**
   This issue needs to be solved prior to #134

**Comment by aaryankotharii** [comment]
Hey, Can this issue be assigned to me?
The pr for this issue needs to be reviewed before #136

**Comment by yugantarjain** [comment]
> Hey, Can this issue be assigned to me?
> The pr for this issue needs to be reviewed before #136

Assigned

**Comment by aaryankotharii** [comment]
@yugantarjain pr made!
