### ISSUE TITLE
Update app for Xcode 12 (UI fixes)

### ISSUE THREAD

**Issue by yugantarjain** [anitab-org/mentorship-ios#141]
**Is your feature request related to a problem? Please describe.**
When built on Xcode 12, the app's UI isn't ideal. Some small changes in code are required for iOS 14 to restore the app's UI to the way it was designed.

**Describe the solution you'd like**
Project shall be built on Xcode 12 and small changes in code must me made wherever required to match its UI to the [screenshots](https://github.com/yugantarjain/mentorship-ios/blob/screenshots/Docs/Screenshots.md) available in readme.
Notable screens to be fixed: Home, Profile, Editor, Send Request, and Relation Screen.

Additionally, in Xcode 12, SwiftUI automatically manages keyboard state and shifts UI upwards if required, hence, the keyboard aware modifier shall be removed.

**Mocks**
UI problems with Xcode 12
| Xcode 11 | Xcode 12 |
| --------- | --------- |
| <img width="501" alt="Home" src="https://user-images.githubusercontent.com/31164725/94987064-284d3280-0581-11eb-8ef2-02dad57f694e.png"> | <img width="497" alt="image" src="https://user-images.githubusercontent.com/31164725/94987051-1cfa0700-0581-11eb-9f61-5e92165aac3f.png"> |

**Comment by yugantarjain** [comment]
@anitab-org/mentorship-ios-maintainers before making this issue available, I'd like to get your approval on this.

**Comment by aaryankotharii** [comment]
@yugantarjain If we begin building this project on Xcode 12, we can also add a lot of new features that SwiftUI 2.0 has to offer.  For example: 
- Appstorage wrapper for persistence.
- TextEditors for notes in requests.
- Disclosure Groups in RelationDetailList.

**Comment by yugantarjain** [comment]
> @yugantarjain If we begin building this project on Xcode 12, we can also add a lot of new features that SwiftUI 2.0 has to offer. For example:
> 
> * Appstorage wrapper for persistence.
> * TextEditors for notes in requests.
> * Disclosure Groups in RelationDetailList.

Yes!

**Comment by sunjunkie** [comment]
I think what is discussed here should be separated into 2 issues. First, create an issue that describes the 'bug' in the app that occurs when built in XCode 12 (or iOS 14?) Currently it is not clear what the exact issues are (capitalization?, missing tasks?). It is also not clear if the issues are due to Xcode 12 or iOS 14? Use the Bug Report format for this when creating a new issue.
Second, if we want to add new features or refactor code due to new SwiftUI features, this should be a separate issue. I think the Feature Request format for the issue would be a good format.

**Comment by yugantarjain** [comment]
> I think what is discussed here should be separated into 2 issues. First, create an issue that describes the 'bug' in the app that occurs when built in XCode 12 (or iOS 14?) Currently it is not clear what the exact issues are (capitalization?, missing tasks?). It is also not clear if the issues are due to Xcode 12 or iOS 14? Use the Bug Report format for this when creating a new issue.
> Second, if we want to add new features or refactor code due to new SwiftUI features, this should be a separate issue. I think the Feature Request format for the issue would be a good format.

1. This issue is specifically for UI fixes (have made it explicit under mocks). It's probably not a bug, but just how SwiftUI is on Xcode 12. I wanted an approval beforehand to be sure that we'll make Xcode 12 the default for the project now...
2. Surely

**Comment by yugantarjain** [comment]
@sunjunkie should I make this issue available for contributors? And, do we still need to update the description or is it fine now?

**Comment by sunjunkie** [comment]
@yugantarjain Go ahead and make this available. The issue is fine as you describe it. I just didn't want the suggestions by @aaryankotharii above to be included in the PR. They should be broken out into a separate issue instead.

**Comment by aaryankotharii** [comment]
Hey, I would like to work on this issue.

**Comment by yugantarjain** [comment]
> Hey, I would like to work on this issue.

Sure, assigned. Thanks!
