### ISSUE TITLE
Create unit and UI tests for Home Screen

### ISSUE THREAD

**Issue by vatsalkul** [anitab-org/mentorship-ios#30]
## Description
As a developer, I need to ensure the quality of app, so that It will not crash when in use

### Update [Required]
- [ ] Create unit, UI tests for home screen.
- [ ] Add different test cases to test the behaviour of the dashboard.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by yugantarjain** [comment]
Done in PR #105 #118
