### ISSUE TITLE
feat: Create member list UI 

### ISSUE THREAD

**Issue by sunjunkie** [anitab-org/mentorship-ios#31]
## Description
As a user,
I need to see all the members of the community,
so that I can choose a member to establish a relation with.
## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] A UI screen showing a list of all current community members
- [ ] UI follows project UI guidelines

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours

**Comment by annabauza** [comment]
@ginny I can't see implementing api endpoint for this task.
