### ISSUE TITLE
feat: Navigate from members list to details screen for a member

### ISSUE THREAD

**Issue by sunjunkie** [anitab-org/mentorship-ios#32]
## Description
As a user,
I need to choose a member from the list of members,
so that I can the details for that member.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] User can select a member from the list
- [ ] User can navigate to a details screen for that member.
- [ ] User can navigate back from the details screen to the member list screen.
- [ ] UI follows project UI guidelines

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours

**Comment by annabauza** [comment]
we can navigate to empty screen for now.

**Comment by yugantarjain** [comment]
I think the PR removes those files. That is a required step for gitignore to work properly.
git rm --cached filepath caused that.
