### ISSUE TITLE
feat: Create tests for members list UI

### ISSUE THREAD

**Issue by sunjunkie** [anitab-org/mentorship-ios#33]
## Description
As a developer,
I need to ensure that the UI handles all user input and backend integration correctly with appropriate error handling,
so that I can release this feature to users.

### Update [Required]
- [ ] Unit tests cover integration with backend
- [ ] Unit tests cover possible error conditions
- [ ] UI tests ensure the existence and correct interaction of UI elements

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours

**Comment by yugantarjain** [comment]
Done in PR #105
