### ISSUE TITLE
Fix broken links in readme file

### ISSUE THREAD

**Issue by yugantarjain** [anitab-org/mentorship-ios#34]
**Describe the bug**
The hyperlinks of "configuring remotes", "contributing and developing a feature", and "contributing guidelines" under the contributing section in the readme file are invalid.

**To Reproduce**
1. Go to readme file.
2. Click on the stated links under contributing heading.
3. See error

**Expected behavior**
The link should redirect to the correct web page.

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [safari]
 - Version [e.g. 13]

**Comment by lwpamihiranga** [comment]
Hi there, can I claim this issue to fix?

**Comment by sunjunkie** [comment]
@lwpamihiranga Yes, I will assign this to you.

**Comment by lwpamihiranga** [comment]
@sunjunkie Thank you for assigning me. I fixed the issue and created the pull request. 🙂
