### ISSUE TITLE
Implement Member Detail Page UI

### ISSUE THREAD

**Issue by yugantarjain** [anitab-org/mentorship-ios#43]
## Description
As a user, I need to see the complete details about a member so I could know more about the community members and send relation requests.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] Develop member detail screen
- [ ] The screen shall show all available details about the member tapped in list screen
- [ ] Actual data should be used, taken from members list screen
- [ ] The screen should have a button for sending request
- [ ] Send request screen should be included

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[6] hours

**Comment by sunjunkie** [comment]
@yugantarjain I think this is the same as #21. It is an epic already. I'll create the tasks for the epic.

**Comment by yugantarjain** [comment]
@sunjunkie I meant this issue to be a task, I've made the wording more clear. We can use this only for the UI task now by doing some edits (if required).

There are three more tasks after this that have to be created - 
1. Backend integration to send request
2. Unit tests
3. UI tests

Thanks!
