### ISSUE TITLE
feat: Get member details from the backend

### ISSUE THREAD

**Issue by sunjunkie** [anitab-org/mentorship-ios#45]
## Description
As a developer,
I need to connect to the backend,
so that I can send relation requests to the member.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] Relation requests are posted to the backend.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours

**Comment by yugantarjain** [comment]
We only need to use the api for sending a request. The data is already loaded in the members list screen and is passed from there.

**Comment by sunjunkie** [comment]
Se we don't need this task, right?

**Comment by yugantarjain** [comment]
Yes, let's just edit this to consuming backend endpoint to send relation requests.
