### ISSUE TITLE
test: create tests for Member Details feature

### ISSUE THREAD

**Issue by sunjunkie** [anitab-org/mentorship-ios#46]
## Description
As a developer,
I need create unit tests for the member detail code,
so that I can be confident the code is working properly.

### Update [Required]
- [ ] Unit tests are available for this feature.
- [ ] UI tests are available for this feature.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours

**Comment by yugantarjain** [comment]
Done in PR #105
