### ISSUE TITLE
Create UI for Feedback Screen

### ISSUE THREAD

**Issue by ApheleiaS** [anitab-org/mentorship-ios#53]
## Description
As a user,
I need to give feedback and as questions,
so that I can better use and understand the app.

### Update [Required]
- [ ] Add a top bar to the page saying its "Feedback"
- [ ] Add TextBox input field for Feedback
- [ ] Add a back button to navigate back to home to the top bar of the page
- [ ] Use Swift UI, MVVM pricinciples
- [ ] All style items must be configurable
- [ ] Strings should be Localizable
- [ ] Prepare UI to link with Feedback Backend 
- [ ] UI follows agreed guidelines

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by mitchell-frost** [comment]
Can I work on this issue if it's still open?

**Comment by yugantarjain** [comment]
Hi @mitchell-frost! Thanks for your interest in contributing to the Mentorship iOS app! This was a task for the GSoC 2020 program, however, it was later realized that the backend doesn't has a feedback API yet. Hence, this is effectively closed for now.
However, we do have other open issues that you can work on, just make sure they aren't marked for the GSoC program. Thanks and all the best!

**Comment by mitchell-frost** [comment]
> Hi @mitchell-frost! Thanks for your interest in contributing to the Mentorship iOS app! This was a task for the GSoC 2020 program, however, it was later realized that the backend doesn't has a feedback API yet. Hence, this is effectively closed for now.
> However, we do have other open issues that you can work on, just make sure they aren't marked for the GSoC program. Thanks and all the best!

Thanks! I'll do that

**Comment by yugantarjain** [comment]
Backend API doesn't exist.
