### ISSUE TITLE
UI and Unit tests for Settings page, About screen, Feedback Screen 

### ISSUE THREAD

**Issue by ApheleiaS** [anitab-org/mentorship-ios#55]
## Description
Tests for the Settings, About and Feedback Screen

### Update [Required]
- [ ] Add UI Tests
- [ ] Add Unit Tests
- [ ] Ensure good coverage

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

**Comment by yugantarjain** [comment]
Done in PR #105
