### ISSUE TITLE
fix: Set keyboard type of email entry text fields 

### ISSUE THREAD

**Issue by sunjunkie** [anitab-org/mentorship-ios#65]
**Describe the bug**
When entering an email address in the signup and login screens, a normal keyboard appears instead of the keyboard for email addresses. The email keyboard has the '@' symbol readily available as well as other email specific features.

**To Reproduce**
1. Go to signup or login screen.
2. Start typing an email address into the email entry field.
4. See a normal keyboard (no '@' visible)

**Expected behavior**
The email keyboard should appear ('@' is visible and a long press on "." shows a list of common top-level domains.

**Screenshots**
Keyboard screenshot: 
![EmailKeyboard](https://user-images.githubusercontent.com/399376/84827958-1f3c5380-afda-11ea-9f79-9888aea7d407.jpeg)

**Smartphone:**
 - Device: iPhones
 - OS: iOS 13.5

**Comment by garima-bothra** [comment]
Hey. I'd like to work on this issue. Can you assign this to me?
