### ISSUE TITLE
test: UI and unit tests for tasks screen

### ISSUE THREAD

**Issue by vatsalkul** [anitab-org/mentorship-ios#76]
## Description
As a developer, I need to ensure the quality of app, so that It will not crash.

### Update [Required]
- [ ]  Create unit tests for tasks screen/code.
- [ ]  Add different test cases to test the behaviour of app.
- [ ]  Create UI tests for tasks screens.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by yugantarjain** [comment]
Done in PR #105
