### ISSUE TITLE
Consume backend endpoint for login/registration.

### ISSUE THREAD

**Issue by vatsalkul** [anitab-org/mentorship-ios#8]
## Description
As a user, I want to register an account so I can log into the app. 
Implement login endpoints also, as a user want to login to the account
Backend Repo Link: https://github.com/anitab-org/mentorship-backend

### Update [Required]

- [ ] If login fails - user should receive proper feedback - email/password is wrong.
- [ ] If login successfully  - user should het to the main dashboard and save the access token for future login.
- [ ] If registration complete user receive proper feedback - User need to confirm the email address.
- [ ] If registration fails - user should receive proper feedback - too short username, too weak password, etc.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

**Comment by annabauza** [comment]
@vatsalkul can we add login as well?

**Comment by vatsalkul** [comment]
@annabauza Done
