### ISSUE TITLE
As a User, I want the password to appear as '*' while changing password

### ISSUE THREAD

**Issue by garima-bothra** [anitab-org/mentorship-ios#97]
**Describe the bug**
When entering a password in the change password screen, the text appears normal and is visible as regular characters. The secure key text makes sure password is visible on the screen as '*' not text.
**To Reproduce**
1. Go to 'Settings' page
2. Click on 'Change Password
3. Start typing a password, normal text appears

**Expected behavior**
Password visible as '*' instead of characters

**Screenshots**
<img width="350" alt="Screenshot 2020-07-15 at 4 39 07 AM" src="https://user-images.githubusercontent.com/48411560/87484940-2300db80-c655-11ea-952e-42e77d79bb36.png">

**Smartphone (please complete the following information):**
 - Device: iPhones
 - OS: iOS 13.5

**Comment by yugantarjain** [comment]
We can also add the requirement that auto capitalization should be turned off in this issue.

**Comment by yugantarjain** [comment]
@anitab-org/mentorship-ios-maintainers seems like a good first issue too...
What do you think?

**Comment by gsnsg** [comment]
Can I work on this issue ?

**Comment by sunjunkie** [comment]
@gsnsg Per the [Contribution Guidelines](https://github.com/anitab-org/mentorship-ios/blob/develop/.github/contributing_guidelines.md), you may not submit a PR before getting approval to work on the issue. In any case, the PR contains the pod files which re not to be checked in.

**Comment by gsnsg** [comment]
Okay then I'll delete my PR

**Comment by yugantarjain** [comment]
@sunjunkie are we assigning it?

**Comment by gsnsg** [comment]
@yugantarjain  Can I work on this issue ?

**Comment by yugantarjain** [comment]
> @yugantarjain Can I work on this issue ?

Sure! Thanks a lot for your patience and interest in contributing to the Mentorship iOS project! Assigned.

**Comment by yugantarjain** [comment]
Resolved in PR #138
