### ISSUE TITLE
bug: empty and completed tasks

### ISSUE THREAD

**Issue by sunjunkie** [anitab-org/mentorship-ios#98]
**Describe the bug**
Several issues exist in the task feature:

A. A task with an empty description is allowed
B. When a task is 'checked' as completed, the task is moved to the Tasks Done section but the radio button is not checked.

**To Reproduce**
1. Go to Relation tab
2. Click on 'Add Task'
3. Click 'Add' without entering a task description
4. See an empty task in the Tasks To Do section on the Relation tab.
5. Mark a task as complete (click on the radio button)
6. The task is not marked as complete even though it is moved to the Tasks Done section
7. Select the Home tab and then the Relation tab. The task is now marked as complete.

**Expected behavior**
A. The task description should be required before the Add button is enabled.
B. The task should be marked as complete immediately when it is moved to the Tasks Done section.

**Screenshots**
![Simulator Screen Shot - iPhone 8 Plus - 2020-07-14 at 22 17 22](https://user-images.githubusercontent.com/399376/87507176-c59f6700-c621-11ea-911c-873851498196.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus
 - OS: iOS 13.5

**Comment by mitchell-frost** [comment]
Can I work on this issue?

**Comment by yugantarjain** [comment]
Issue 'B' is a SwiftUI bug and has been resolved by Apple in Xcode 12.

**Comment by sunjunkie** [comment]
@mitchell-frost This issue is for the GSoC program only.
